export const WeatherImages: { [index: string]: any } = {
    '01d': require('WeatherImage/sun.png'),
    '02d': require('WeatherImage/littleCloud.png'),
    '03d': require('WeatherImage/cloud.png'),
    '04d': require('WeatherImage/manyCloud.png'),
    '09d': require('WeatherImage/rain.png'),
    '10d': require('WeatherImage/rain.png'),
    '11d': require('WeatherImage/lightning.png'),
    '13d': require('WeatherImage/snow.png'),
    '01n': require('WeatherImage/sun.png'),
    '02n': require('WeatherImage/littleCloud.png'),
    '03n': require('WeatherImage/cloud.png'),
    '04n': require('WeatherImage/manyCloud.png'),
    '09n': require('WeatherImage/rain.png'),
    '10n': require('WeatherImage/rain.png'),
    '11n': require('WeatherImage/lightning.png'),
    '13n': require('WeatherImage/snow.png'),
    '50n': require('WeatherImage/mist.png'),
    '50d': require('WeatherImage/mist.png'),
};
export const WeatherDescription: { [index: string]: any } = {
    '01d': '맑음',
    '02d': '구름약간',
    '03d': '구름',
    '04d': '구름많음',
    '09d': '비',
    '10d': '비',
    '11d': '번개',
    '13d': '눈',
    '01n': '맑음',
    '02n': '구름약간',
    '03n': '구름',
    '04n': '구름많음',
    '09n': '비',
    '10n': '비',
    '11n': '번개',
    '13n': '눈',
    '50n': '안개',
    '50d': '안개',
};
