export const Dummy = [
    {
        area: '서울',
        comment: '거의 축구 네덜란드국가대표룩',
        date: '2021-07-25T05:28:42',
        dressResponses: [
            {
                dressId: 761,
                dressName: '주황 반팔',
                dressType: 'TOP',
                partialMood: 'GOOD',
            },
            {
                dressId: 762,
                dressName: '주황 반바지',
                dressType: 'BOTTOM',
                partialMood: 'GOOD',
            },
        ],
        humidity: 25,
        measureId: 763,
        mood: 'GOOD',
        tempInfo: '폭염 주의보',
        temperatureHigh: 33.2,
        temperatureLow: 22.3,
        userConstitution: 'HOT',
        userId: 'testuser1',
        userName: 'testUser',
    },
    {
        area: '서울',
        comment: '거의 축구 브라질국가대표룩',
        date: '2021-07-23T05:28:42',
        dressResponses: [
            {
                dressId: 751,
                dressName: '노랑 반팔',
                dressType: 'TOP',
                partialMood: 'GOOD',
            },
            {
                dressId: 752,
                dressName: '초록 반바지',
                dressType: 'BOTTOM',
                partialMood: 'GOOD',
            },
        ],
        humidity: 20,
        measureId: 753,
        mood: 'GOOD',
        tempInfo: '습함',
        temperatureHigh: 27.2,
        temperatureLow: 23.3,
        userConstitution: 'HOT',
        userId: 'testuser1',
        userName: 'testUser',
    },
    {
        area: '서울',
        comment: '셔츠를 입기에 너무 덥다',
        date: '2021-08-10T05:28:42',
        dressResponses: [
            {
                dressId: 694,
                dressName: '여름 긴팔 셔츠',
                dressType: 'OUTER',
                partialMood: 'VERYHOT',
            },
            {
                dressId: 695,
                dressName: '하얀색 무지 반팔',
                dressType: 'TOP',
                partialMood: 'GOOD',
            },
            {
                dressId: 696,
                dressName: '검정 반바지',
                dressType: 'BOTTOM',
                partialMood: 'GOOD',
            },
            {
                dressId: 697,
                dressName: '컨버스 로우',
                dressType: 'SHOES',
                partialMood: 'GOOD',
            },
        ],
        humidity: 58,
        measureId: 698,
        mood: 'VERYHOT',
        tempInfo: '맑음',
        temperatureHigh: 31,
        temperatureLow: 22,
        userConstitution: 'HOT',
        userId: 'jjjj',
        userName: 'j97',
    },
    {
        area: '서울',
        comment: '너무 덥다',
        date: '2021-08-12T05:28:42',
        dressResponses: [
            {
                dressId: 679,
                dressName: '검정 긴팔',
                dressType: 'TOP',
                partialMood: 'HOT',
            },
            {
                dressId: 680,
                dressName: '여름 청바지',
                dressType: 'BOTTOM',
                partialMood: 'HOT',
            },
            {
                dressId: 649,
                dressName: '반스 올드스쿨',
                dressType: 'SHOES',
                partialMood: 'HOT',
            },
        ],
        humidity: 58,
        measureId: 681,
        mood: 'VERYHOT',
        tempInfo: '대체로 흐림',
        temperatureHigh: 32,
        temperatureLow: 23,
        userConstitution: 'COLD',
        userId: 'jslee',
        userName: 'junzzang97',
    },
    {
        area: '서울',
        comment: '반팔티 재질이 좀 더웠다.',
        date: '2021-06-11T05:28:42',
        dressResponses: [
            {
                dressId: 672,
                dressName: '쥐색 반팔티',
                dressType: 'TOP',
                partialMood: 'HOT',
            },
            {
                dressId: 673,
                dressName: '찢청반바지',
                dressType: 'BOTTOM',
                partialMood: 'GOOD',
            },
            {
                dressId: 674,
                dressName: '버켄스탁 샌들',
                dressType: 'SHOES',
                partialMood: 'GOOD',
            },
        ],
        humidity: 12,
        measureId: 675,
        mood: 'HOT',
        tempInfo: '구름 많음',
        temperatureHigh: 29.5,
        temperatureLow: 23.3,
        userConstitution: 'COLD',
        userId: 'testuser3',
        userName: 'testUser3',
    },
    {
        area: '서울',
        comment: '적당한 날씨',
        date: '2021-08-08T05:28:42',
        dressResponses: [
            {
                dressId: 666,
                dressName: '하늘색 무지 반팔',
                dressType: 'TOP',
                partialMood: 'GOOD',
            },
            {
                dressId: 667,
                dressName: '나이키 검정 반바지',
                dressType: 'BOTTOM',
                partialMood: 'GOOD',
            },
            {
                dressId: 661,
                dressName: '크림색 이지부스트',
                dressType: 'SHOES',
                partialMood: 'HOT',
            },
        ],
        humidity: 57,
        measureId: 668,
        mood: 'GOOD',
        tempInfo: '흐림',
        temperatureHigh: 31,
        temperatureLow: 24.2,
        userConstitution: 'COLD',
        userId: 'jslee',
        userName: 'junzzang97',
    },
    {
        area: '서울',
        comment: '크게 덥지 않았다.',
        date: '2021-08-10T05:28:42',
        dressResponses: [
            {
                dressId: 647,
                dressName: '나이키 반팔',
                dressType: 'TOP',
                partialMood: 'GOOD',
            },
            {
                dressId: 648,
                dressName: '회색 조거 팬츠',
                dressType: 'BOTTOM',
                partialMood: 'GOOD',
            },
            {
                dressId: 649,
                dressName: '반스 올드스쿨',
                dressType: 'SHOES',
                partialMood: 'GOOD',
            },
        ],
        humidity: 57,
        measureId: 650,
        mood: 'GOOD',
        tempInfo: '맑음',
        temperatureHigh: 31.3,
        temperatureLow: 24,
        userConstitution: 'COLD',
        userId: 'jslee',
        userName: 'junzzang97',
    },
];
