export const Dummy = [
    {
        measureId: 14,
        userId: 'testuser1',
        userName: 'testUser',
        userConstitution: 'HOT',
        date: '2021-08-05T05:28:42',
        tempInfo: '맑음',
        temperatureHigh: 31.5,
        temperatureLow: 26.3,
        humidity: 60.0,
        area: '부산',
        mood: 'GOOD',
        comment: '전반적으로 괜찮았다.',
        dressResponses: [
            {
                dressId: 10,
                dressName: '검정 가디건',
                dressType: 'OUTER',
                partialMood: 'GOOD',
            },
            {
                dressId: 11,
                dressName: '아디다스 후드티',
                dressType: 'TOP',
                partialMood: 'GOOD',
            },
            {
                dressId: 12,
                dressName: '카고 반바지',
                dressType: 'BOTTOM',
                partialMood: 'COLD',
            },
            {
                dressId: 13,
                dressName: '반스 올드스쿨',
                dressType: 'SHOES',
                partialMood: 'HOT',
            },
        ],
    },
    {
        measureId: 234,
        userId: 'testuser1',
        userName: 'testUser',
        userConstitution: 'HOT',
        date: '2021-08-04T05:28:42',
        tempInfo: '구름 많음',
        temperatureHigh: 31.5,
        temperatureLow: 24.3,
        humidity: 15.0,
        area: '서울',
        mood: 'COLD',
        comment: '상의는 대체로 더웠으나 하의와 신발은 추웠다.',
        dressResponses: [
            {
                dressId: 1,
                dressName: '회색 가디건',
                dressType: 'OUTER',
                partialMood: 'GOOD',
            },
            {
                dressId: 2,
                dressName: '나이키 후드티',
                dressType: 'TOP',
                partialMood: 'HOT',
            },
            {
                dressId: 3,
                dressName: '연청바지',
                dressType: 'BOTTOM',
                partialMood: 'COLD',
            },
            {
                dressId: 4,
                dressName: '삼선 슬리퍼',
                dressType: 'SHOES',
                partialMood: 'VERY COLD',
            },
        ],
    },
    {
        measureId: 5654,
        userId: 'testuser1',
        userName: 'testUser',
        userConstitution: 'HOT',
        date: '2021-08-04T05:28:42',
        tempInfo: '구름 많음',
        temperatureHigh: 31.5,
        temperatureLow: 24.3,
        humidity: 15.0,
        area: '서울',
        mood: 'COLD',
        comment: '상의는 대체로 더웠으나 하의와 신발은 추웠다.',
        dressResponses: [
            {
                dressId: 1,
                dressName: '회색 가디건',
                dressType: 'OUTER',
                partialMood: 'GOOD',
            },
            {
                dressId: 2,
                dressName: '나이키 후드티',
                dressType: 'TOP',
                partialMood: 'HOT',
            },
            {
                dressId: 3,
                dressName: '연청바지',
                dressType: 'BOTTOM',
                partialMood: 'COLD',
            },
            {
                dressId: 4,
                dressName: '삼선 슬리퍼',
                dressType: 'SHOES',
                partialMood: 'VERY COLD',
            },
        ],
    },
    {
        measureId: 8,
        userId: 'testuser1',
        userName: 'testUser',
        userConstitution: 'COLD',
        date: '2021-08-04T05:28:42',
        tempInfo: '구름 많음',
        temperatureHigh: 31.5,
        temperatureLow: 24.3,
        humidity: 15.0,
        area: '서울',
        mood: 'COLD',
        comment: '상의는 대체로 더웠으나 하의와 신발은 추웠다.',
        dressResponses: [
            {
                dressId: 1,
                dressName: '회색 가디건',
                dressType: 'OUTER',
                partialMood: 'GOOD',
            },
            {
                dressId: 2,
                dressName: '나이키 후드티',
                dressType: 'TOP',
                partialMood: 'HOT',
            },
            {
                dressId: 3,
                dressName: '연청바지',
                dressType: 'BOTTOM',
                partialMood: 'COLD',
            },
            {
                dressId: 4,
                dressName: '삼선 슬리퍼',
                dressType: 'SHOES',
                partialMood: 'VERY COLD',
            },
        ],
    },
    {
        measureId: 9,
        userId: 'testuser1',
        userName: 'testUser',
        userConstitution: '',
        date: '2021-08-04T05:28:42',
        tempInfo: '구름 많음',
        temperatureHigh: 331.5,
        temperatureLow: 24.3,
        humidity: 15.0,
        area: '서울',
        mood: 'COLD',
        comment: '상의는 대체로 더웠으나 하의와 신발은 추웠다.',
        dressResponses: [
            {
                dressId: 1,
                dressName: '',
                dressType: 'OUTER',
                partialMood: 'GOOD',
            },
            {
                dressId: 2,
                dressName: '나이키 후드티',
                dressType: 'TOP',
                partialMood: 'HOT',
            },
            {
                dressId: 3,
                dressName: '연청바지',
                dressType: 'BOTTOM',
                partialMood: '',
            },
            {
                dressId: 4,
                dressName: '삼선 슬리퍼',
                dressType: 'SHOES',
                partialMood: 'VERY COLD',
            },
        ],
    },
];
